AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template to create SNS topic, SQS queue, and Lambda function for DALVacationHome Notification module.

Resources:
  UserNotificationTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: 'UserNotifications'

  BookingRequestQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: 'BookingRequestQueue'

  BookingApprovalFunction:
    Type: 'AWS::Lambda::Function'
    Properties: 
      FunctionName: 'BookingApprovalFunction'
      Handler: 'index.lambda_handler'
      Role: 
        Fn::GetAtt: 
          - LambdaExecutionRole
          - Arn
      Code: 
        S3Bucket: 'your-bucket-name'
        S3Key: 'your-code-file.zip'
      Runtime: 'python3.8'
      Environment:
        Variables:
          SNS_TOPIC_ARN: 
            Ref: UserNotificationTopic

  LambdaSQSTrigger:
    Type: 'AWS::Lambda::EventSourceMapping'
    Properties:
      BatchSize: 10
      EventSourceArn: 
        Fn::GetAtt: 
          - BookingRequestQueue
          - Arn
      FunctionName: 
        Ref: BookingApprovalFunction

  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'LambdaExecutionRole'
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement: 
          - Effect: 'Allow'
            Principal: 
              Service: 'lambda.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'LambdaSQSPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'
              - Effect: 'Allow'
                Action: 
                  - 'sns:Publish'
                Resource: 
                  Ref: UserNotificationTopic
              - Effect: 'Allow'
                Action: 
                  - 'sqs:ReceiveMessage'
                  - 'sqs:DeleteMessage'
                  - 'sqs:GetQueueAttributes'
                Resource: 
                  Fn::GetAtt: 
                    - BookingRequestQueue
                    - Arn

Outputs:
  SNSTopicArn:
    Description: 'SNS Topic ARN'
    Value: 
      Ref: UserNotificationTopic
  SQSQueueURL:
    Description: 'SQS Queue URL'
    Value: 
      Ref: BookingRequestQueue
  LambdaFunctionArn:
    Description: 'Lambda Function ARN'
    Value: 
      Ref: BookingApprovalFunction
