imports:
  - path: pubsub.py
  - path: cloud_function.py
  - path: firestore.py

resources:
  - name: customer-messages-topic
    type: pubsub.py
    properties:
      topic: customer-messages
      project: dalvacationhome-dev

  - name: property-agent-messages-topic
    type: pubsub.py
    properties:
      topic: property-agent-messages
      project: dalvacationhome-dev

  - name: process-customer-messages-function
    type: cloud_function.py
    properties:
      runtime: python310
      entryPoint: hello_pubsub
      sourceArchiveUrl: 
      eventTrigger:
        eventType: google.pubsub.topic.publish
        resource: $(ref.customer-messages-topic.name)
      location: us

  - name: firestore-setup
    type: firestore.py
